module_name: Social Sharing Block
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - social sharing
  - facebook share
  - twitter share
description_short: The Social Sharing module allows you to place a block on the product pages letting customers share your products.
description: description.md
images:
  - image-1.png
license: AFL